### ISSUE TITLE
Anrop av SPARQL-endepunkt - Unauthorized 

### ISSUE THREAD

**Issue by olemartin-BP** [buildingsmart-norway/maskinlesbar_V441#11]
Hei, jeg ønsket å se om jeg kunne lage en web app som tok i bruk ontologien direkte via http-kall fra en backend.  Jeg har forsøkt å implementere kode-eksempelet men får "Unauthorized" som respons.  Trenger man å registrere app'er som skal ta i bruk ontologien?
![image](https://user-images.githubusercontent.com/78475219/107041807-3cb86a80-67c1-11eb-9ae6-d3f88d1fcc35.png)

**Comment by SigveMartin** [comment]
Man skal ikke trenge å registrere app'er. Det kan evnt @iSkogli bekrefte. Får ikke testet selv akkurat nå, men kan gi tilbakemelding når jeg har fått testet. 

@hkgrani måtte du endre på eksempelet for å få det til å fungere?

**Comment by hkgrani** [comment]
Det skal ikke være nødvendig å registrere apper. Endepunktet skal være åpent tilgjengelig.

Vi hadde et tilsvarende tilfelle i BOLC-prosjektet der vi fikk beskjed om manglende tilgang. Der var feilen at utvikleren spurte mot v440 repositoriet (som også finnes men er sperret), mens det åpne repositoriet er V440 (med stor V). Dette bør en vurdere å rydde i

Men tilbake til denne issuen. Hvis en kjører en enkel spørring som denne

```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?uri ?label WHERE { ?uri rdfs:label ?label . FILTER(?label="Skade"@no)}
```

i curl på denne måten

```
curl -X GET 'http://rdfspatial.vegdata.no:7200/repositories/v441?query=SELECT%20%3Furi%20%3Flabel%20WHERE%20%7B%20%3Furi%20rdfs%3Alabel%20%3Flabel%20.%20FILTER(%3Flabel%3D%22Skade%22%40no)%7D'
```

Bør en få svar i konsollet

```
uri,label
http://rdf.vegdata.no/bridge/v441/v441-owl#Skade,Skade
```

Noe som viser at endpoint er åpent. Så det er enten noe feil med hvordan koden genererer spørring eller at spørringen ber om data som ligger utenfor det tillatte. Har du mulighet for å fange opp requesten du sender fra klienten @olemartin-BP , så kan vi se hva som er feil

**Comment by olemartin-BP** [comment]
Ok, jeg ser du benytter liten v i uri'en i svaret ditt, og at det er oppgitt stor v i c#-eksempelet på readme'en. Når jeg gjør det jeg antar er en representativ initiell test på endpunktene vha nettleseren erfarer jeg at 'V441' gir 'Unauthorized (HTTP status 401)',og 'v441' gir 'Missing parameter: query' (altså tilgang, men manglende input query). Det å benytte liten v ser også ut til å løse problemet med c#-eksempelet. Kan det være at liten/stor v-konvensjonen er omvendt for v441 sammenlignet med v440?

![image](https://user-images.githubusercontent.com/78475219/107118730-ec094600-6882-11eb-8d92-bcd08e786f25.png)
![image](https://user-images.githubusercontent.com/78475219/107118736-f7f50800-6882-11eb-9c6f-092ace350d53.png)

![image](https://user-images.githubusercontent.com/78475219/107118836-b7e25500-6883-11eb-9838-2fdefa1239ee.png)

**Comment by hkgrani** [comment]
Hei. Ja det stemmer nok. Det er implementert forskjellig i de to ontologiene og det virker som om C# eksemplet er litt "copy/paste" fra V440 repoet

Her bør det standardiseres så vi unngår slike utfordringer. Repo-navnet i triplestore er ikke en del av ontologien så ser det lett kan bli slik.

Tar du den videre til rett person @JanErikHoel ?

**Comment by larswik** [comment]
Jag tror att dokumentationen nu ska vara uppdaterad när det gäller "V" vs "v".

**Comment by larswik** [comment]
Se issue https://github.com/buildingsmart-norway/maskinlesbar_V441/issues/12
