### ISSUE TITLE
Subklasser vs Instanser i ontologien - hierarki med en spørring?

### ISSUE THREAD

**Issue by hkgrani** [buildingsmart-norway/maskinlesbar_V441#9]
Når jeg sammenligner V441 ontologien med V440 ontologien så ser jeg en del eksempler der V441 benytter "instanser" i stedet for "subklasser" i ontologien. Se bilde nedenfor som sammenligner underkategorisering av byggverkselement "Slitelag" med skadeårsak "bruksskade".  

![v441-owl__http___rdf_vegdata_no_bridge_v441_v441-owl______https___raw_githubusercontent_com_buildingsmart-norway_maskinlesbar_V441_master_900_ontologi_v441_v441-owl_ttl__and_v440-owl__http___rdf_vegdata_no_V440_v440-owl______http___rdf_vegd](https://user-images.githubusercontent.com/1169681/106271203-6e648b00-622f-11eb-8310-a7f91f510ea4.png)

For å bygge hierarkisk plukkliste for å registrere skadeårsak kan vi først gjøre spørring på klasser

```
select distinct ?class ?name
where
{
    ?class rdfs:subClassOf* v441:Skadearsak.
    OPTIONAL {?class rdfs:label ?name} .
    FILTER NOT EXISTS { ?subclass rdfs:subClassOf ?class }
}
```

For så å be om instanser for hver av klassene
```
select distinct ?uri ?code ?name ?class
where
{
    ?uri a v441:Bruksskade .   
    ?uri v441:kode ?code.
    ?uri rdfs:label ?name.
}
```

Finnes det en måte å spørre etter hele dette treet med "klasser og instanser" i en spørring slik vi fikk hjelp til med klassehierarki her https://github.com/buildingsmart-norway/maskinlesbar_v440/issues/17 ? @larswik

**Comment by hkgrani** [comment]
Og litt datamodelleringsmessig - Er forholdet mellom subclasser og deres "instanser", tilsvarende konsepter som IFCsine typer og deres underinndeling i "typeEnums", f. eks 
https://standards.buildingsmart.org/IFC/DEV/IFC4_2/FINAL/HTML/schema/ifchvacdomain/lexical/ifcairterminaltype.htm med
https://standards.buildingsmart.org/IFC/DEV/IFC4_2/FINAL/HTML/schema/ifchvacdomain/lexical/ifcairterminaltypeenum.htm

**Comment by SigveMartin** [comment]
Takk for godt spørsmål og innspill @hkgrani! Dette må nok @larswik svare nærmere på.

**Comment by larswik** [comment]
Jag tittar på denna och återkommer!! Ett alternativ är naturligtvis att göra klasser av allt. Men eftersom exempelvis Skadeårsak bara är en kodlista som en egenskap till en skade och att skadeårsaken inte har några uppgifter i sig så känns detta naturligare och riktigare. Mönstret följer just nu det som anges i "Semantic modelling and linking standard", kapitlet om "Enumeration datatypes".

**Comment by hkgrani** [comment]
Den er grei. Det gir mening og samsvarer bra med IFC sine typeenums. Der legger de og til en ekstre plukkliste uten at det kreves egen klasse dersom attributter og egenskapssett er felles

Sjekk gjerne om det er mulig å hente alt som en spørring. Hvis ikke er ikke det krise

**Comment by larswik** [comment]
Jag satte på enklaste sätt ihop en fråga som plockar fram instanserna för de klasser som finns på nedersta nivån i strukturen. Testa och se om detta hjälper.
```
select distinct ?class ?name ?uri ?code ?name
where
{
    ?class rdfs:subClassOf* :Skadearsak.
    OPTIONAL {?class rdfs:label ?name} .
    FILTER NOT EXISTS { ?subclass rdfs:subClassOf ?class }
    ?uri a ?class .   
    optional {
    	?uri :kode ?code.
    }
    optional {
	?uri rdfs:label ?name.}
    }
```

**Comment by hkgrani** [comment]
Jepp det funker. Takker

Legger inn en liten justering jeg måtte gjøre for å få det til å spille i web-konsollet i tilfelle andre som leser dette vil prøve i web konsollet (la in v441 prefix)

```
prefix v441: <http://rdf.vegdata.no/bridge/v441/v441-owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select distinct ?class ?name ?uri ?code ?name

where

{
    ?class rdfs:subClassOf* v441:Skadearsak.
    OPTIONAL {?class rdfs:label ?name} .
    FILTER NOT EXISTS { ?subclass rdfs:subClassOf ?class }
    ?uri a ?class .   
    optional {
    	?uri v441:kode ?code.
    }
    optional {
	?uri rdfs:label ?name.}
    }
```

**Comment by hkgrani** [comment]
For ordens skyld i tilfelle noen førsøker denne spørringen så mp den endres til 

```
prefix v441: <http://rdf.vegdata.no/bridge/v441/core/v441-owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select distinct ?class ?name ?uri ?code ?name

where

{
    ?class rdfs:subClassOf* v441:Skadearsak.
    OPTIONAL {?class rdfs:label ?name} .
    FILTER NOT EXISTS { ?subclass rdfs:subClassOf ?class }
    ?uri a ?class .   
    optional {
    	?uri v441:kode ?code.
    }
    optional {
	?uri rdfs:label ?name.}
    }
```

Dette som en følge av #13
